---
label: Default
hide_body: true
fields:
- name: titulo
  type: text
  config:
    required: false
  label: Titulo
- name: conteudo
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Conteudo
